steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/microservices-course-444616/image-registry/products-ms-prod",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/microservices-course-444616/image-registry/products-ms-prod",
      ]
options:
  logging: CLOUD_LOGGING_ONLY